"""modify appointments table (start/end time)

Revision ID: 3b947e4001e1
Revises: 97263cb59615
Create Date: 2026-06-15 16:05:51.734892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b947e4001e1'
down_revision: Union[str, Sequence[str], None] = '97263cb59615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('datetime', sa.DATETIME(), nullable=False))
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
