"""create schedules table and modify users

Revision ID: 9530aa25e64e
Revises: e9824cfcc1fd
Create Date: 2026-06-03 10:45:14.073479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9530aa25e64e'
down_revision: Union[str, Sequence[str], None] = 'e9824cfcc1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    user_role_enum = sa.Enum('client', 'professional', 'admin', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('role', user_role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('schedules')

    user_role_enum = sa.Enum('client', 'professional', 'admin', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
